### ISSUE TITLE
data-remote too slow

### ISSUE THREAD

**Issue by CrasherGIT** [1000hz/bootstrap-validator#384] opened 2016-07-26 12:13 UTC
Hi,

I do have an issue with the remote validation used to check if an email address has already been taken or not. Let me give you an example:

In the email field enter test@test.co (in the database test@test.com has already been taken) since the email does not match the field is validated, after that I complete the email field with the "m" directly press enter to submit the form and that will work, since it is to fast and the data-remote has no time for the validation.

**HTML Code**
```
<form name="register" id="register" data-toggle="validator" method="post"> 
<input id="r-email" name="r-email" type="email" class="form-control" placeholder="<?=$translationTable['email']->value?>" required data-error="<?=$translationTable['formerror-email']->value?>" data-remote="/ajax/register.ajax.php?action=validateQqUserEmail" data-remote-error="<?=$translationTable['formerror-emailinuse']->value?>">
</form>
```

**JS Code**
```
$('form#register').validator().on('submit', function(e) 
{
    if (e.isDefaultPrevented()) 
    {
        // handle the invalid form...
    } 
    else 
    {
        // stop default link actions
        e.preventDefault();
        
        // send the form via ajax to the backend
        $("form#register").ajaxSubmit({
            type: "POST",
            dataType: "JSON",
            url: "/ajax/register.ajax.php",
            data: { action: "create" },
            success: function(data) {
                
            },
            error: function(data) {
                
            }
        });
    }
});	
```

**PHP Code**
```
elseif ( $action == "validateQqUserEmail" ) 
{
	// load initializer
	include( "initializer.inc.php" );
	
	// get variables
	$email = $_GET['r-email'];
	
	if ( Security::validateQqUserEmail($email) )
	{
		// send http OK
		http_response_code(200);
	}
	else
	{
		// send http NOT OK
		http_response_code(418);
	}
}
```

I hope you see my issue. Let me know if I do something wrong or if this is a known problem.

Thanks.

**Comment by 1000hz** [comment] 2016-07-26 15:10
Yup, this is an issue and there isn't a good workaround yet. Adding first-class support for promises/deferred is the next major thing on the roadmap.

Closing as a duplicate of #72.

**Closed by 1000hz** 2016-07-26 15:10 UTC
