### ISSUE TITLE
Is it possible to fire validation on button click outside of a form?

### ISSUE THREAD

**Issue by nicholasalanbrown** [1000hz/bootstrap-validator#89] opened 2015-03-15 04:14 UTC
I have a use case where I'm trying to validate an email address not typed into a form element per se. I'd like to fire this validation based on a click event. How would I go about doing this?

Thanks!

**Comment by 1000hz** [comment] 2015-03-20 18:47
Sounds like this might be a dupe of #74

**Closed by 1000hz** 2015-03-20 18:47 UTC

**Comment by 1000hz** [comment] 2015-04-02 05:31
I might have misunderstood what you were trying to do. It sounds like you don't have a `<form>` element at all? If that's the case, you should just wrap your `<input type="email">` in a `<form id="emailForm">` tag. Then inside of your click handler you can call `$('#emailForm').validator('validate')`.

**Comment by nicholasalanbrown** [comment] 2015-04-08 15:13
Great. Thanks!

**Comment by aishwaryacedcoss** [comment] 2019-08-22 05:53
@1000hz thanks . It helps .
