### ISSUE TITLE
jsdelivr

### ISSUE THREAD

**Issue by nam-co** [1000hz/bootstrap-validator#438] opened 2016-11-13 11:50 UTC
Hi, thanks for the great package, please consider jsdelivr as a CDN option
https://github.com/jsdelivr/jsdelivr/blob/master/CONTRIBUTING.md

Thanks

**Comment by 1000hz** [comment] 2016-11-17 18:28
Duplicate of #383

**Closed by 1000hz** 2016-11-17 18:28 UTC
