### ISSUE TITLE
Separate native validator custom error messages

### ISSUE THREAD

**Issue by romain-granai** [1000hz/bootstrap-validator#241] opened 2015-11-23 13:35 UTC
Hi,

I'm currently trying to validate 2 email forms.
The first on is a basic email and the second must match the first.
What I would like to do is : 
- When the email fields are empty, the error message should be "please enter your email address".
- When the email fields are invalid (not an proper email address), the error message should be "Please enter a valid email".

the problem is that only data-error="something" is available. Is there a way to customize the error message when the field is empty AND a custom message when the field is invalid?

Furthermore, a valid email address should have a "@" AND a "." character to be valid, but actually the plugin make the field valid only if the "@" is present.

Thank you

**Comment by 1000hz** [comment] 2015-11-23 17:47
You can use `data-native` and `data-match` together for the second field, but for the first one, the best you can do at the moment is `data-native="Please enter your email address"` for both the empty state and the invalid state. This will be fixed when I have time to implement #212 for all validation types.

As for the email validation issue, that's not a bug. The `.` isn't required according to the spec. See #31 #178 #190.

**Comment by jonw100** [comment] 2015-12-22 12:16
I must admit I too thought that the email validation was broken when it claimed validity as soon as the @ was present, and reading the spec I thought it did sound like there should be minimum of 2 groups of words separated by a dot.  But then looking at the wikipedia entry
https://en.wikipedia.org/wiki/Email_address#Domain_part
that does contain a few examples of instances where the dot may not be part of an email address, so technically it may well be correct.

But, it would be a nice feature if the email validation could be enhanced to allow for developers to have the *additional* option of insisting on the presence of a dot also for validation success.

**Closed** 2016-07-15 11:52 UTC
Labels: enhancement
