### ISSUE TITLE
problem with select2 plugin

### ISSUE THREAD

**Issue by AviFix** [1000hz/bootstrap-validator#38] opened 2014-09-20 18:48 UTC
hi

when validating a form with the jquery-ui (combobox) plugin.

http://jqueryui.com/autocomplete/#combobox

while validating... all select lists pop open.
example:
http://jsfiddle.net/tLcqs0ak/1/
thanks allot
Avi

**Comment by 1000hz** [comment] 2015-02-05 02:00
Finally got around to tracking the cause of this down. It's because the plugin is triggering an `input` event on all fields to trigger validation.  I need to namespace these event triggers to avoid calling any other third-party input event handlers by accident. It will be fixed in the next release.

**Closed** 2015-02-05 02:39 UTC
Labels: bug

**Comment by AviFix** [comment] 2015-02-05 07:13
Thanks alot

Avi
