### ISSUE TITLE
Select on MAC Safari v9.0.3 fail 

### ISSUE THREAD

**Issue by cyberfuel** [1000hz/bootstrap-validator#293] opened 2016-03-15 19:26 UTC
Hi,

If I use a MAC with Safari (v9.0.3) browser, with the SELECT

```html
<label class="control-label">Country</label>
<select class="form-control" name="country" id="country" required>        
  <option value="" ></option>		
  <option value="USA">USA</option>
  <option value="MEXICO">MEXICO</option>                
  <option value="CANADA">CANADA</option>                
</select>
``` 

This is a BUG, because doesn't work.

Regards.

**Comment by 1000hz** [comment] 2016-03-15 20:43
It looks like a bug in Safari is causing it to erroneously return `false` from `el.checkValidity()` even though `el.validity.valid === true`. I'll put a fix in the next patch release.

**Comment by ddspringle** [comment] 2016-03-18 01:57
Unsure if it's the same issue, but selects do not work in Safari 8 either.

**Comment by goog62** [comment] 2016-03-24 15:47
I think we're experiencing the same problem. On apple devices, SELECT elements containing the REQUIRED attribute appear invalid when a user chooses a value for the first time. If the value gets changed, the validation seems to work properly. Until this gets fixed, we have to remove the REQUIRED attribute and let the server side validation catch the error. Please let me know when the next patch gets released. Thanks!

**Comment by ddspringle** [comment] 2016-03-24 19:27
I left the required attribute in for other browsers and simply don't load the validation JavaScript for Safari browsers... since Safari ignores the required attribute anyway.

**Comment by th0car** [comment] 2016-04-19 20:34
Can this problem even be fixed within the bootstrap-validator? If so - Do you know when the next patch is due?

**Comment by marten-seemann** [comment] 2016-04-20 05:39
I just created a jsFiddle for a bug with *select*s in Safari, and was wondering if this is the same bug that you guys have already found. Maybe you can have a look: https://jsfiddle.net/m4r73n/sqhnox6d/1/

Has anyone of you written a patch or found any workaround?

**Comment by tezro** [comment] 2016-04-22 03:44
Confirmed this bug too. Is there any fix?

**Comment by aegisho** [comment] 2016-05-15 05:16
Rewrite the checkValidity method as workground
it work for me
```javascript
if (/Safari/.test(navigator.userAgent)) {
  HTMLSelectElement.prototype.checkValidity = function checkValidity() {
    return this.validity.valid
  }
}
```

**Comment by marten-seemann** [comment] 2016-05-15 05:19
Note that you're not only matching for actual Safari's here. For example, Chrome also pretends to be a Safari in it's user agent string (see http://www.useragentstring.com/pages/Chrome/).

**Comment by mou0605** [comment] 2016-05-16 03:29
@aegisho 's method work for me, too.

**Comment by podonnel** [comment] 2016-06-01 00:26
Yes, thx @aegisho, working for me too. 

Great project @1000hz

**Comment by MattRiddell** [comment] 2016-06-02 15:58
Yeah same problem here

**Comment by podonnel** [comment] 2016-06-21 01:24
Discovered the workaround from @aegisho doesn't help when the "in-app" browser on iOS is used - like the browser inside the Facebook or Linkedin app. Suspect @marten-seemann's pointing out that just searching for "Safari" in the user agent string is a bit hit and miss. The user-agent string in in-app browsers - which behave differently to the native Safari in ways I haven't worked out - is complex and takes a bit more to identify - but once identified I haven't worked out how to make it work yet. If I do I'll post back, but wonder if anybody else has experience?

**Closed** 2016-07-15 11:52 UTC
