### ISSUE TITLE
$().validator('destroy') block e.isDefaultPrevented()

### ISSUE THREAD

**Issue by giugit** [1000hz/bootstrap-validator#147] opened 2015-06-18 08:35 UTC
I verified that if I use
```js
$().validator('destroy')
```
to reset the forms errors and then
```js
$().validator()
```
to reactivate the validation

this
```js
$('#form').validator().on('submit', function (e) {
  if (e.isDefaultPrevented()) {
    // handle the invalid form...
  } else {
    // everything looks good!
  }
})
```
stop to work

`e.isDefaultPrevented()` is always false

What is possible to do?

Thanks

**Comment by giugit** [comment] 2015-06-25 07:58
Any Help for this?

**Comment by 1000hz** [comment] 2015-07-01 01:27
I can't reproduce this issue. Check out this JSBin.

http://jsbin.com/zojanipaba/1/edit?html,css,js,output

I'm going to close the issue, but feel free to comment again with a JSBin that shows the issue and I'll reopen it.

**Closed by 1000hz** 2015-07-01 01:27 UTC

**Comment by nijinnarayanan** [comment] 2015-08-10 16:48
Here is JSBin: http://jsbin.com/nekekafajo/edit?html,js,output

I have the same issue with modal form controls.

**Comment by 1000hz** [comment] 2015-08-10 18:17
When the validator is destroyed and reinitialized, the handler that prevents default on the submit event becomes bound after your valid/invalid check. Since event handlers run in the order they are bound, you need to make sure your check runs after the validator event handlers, so you'll need to rebind it after the destroy call.

**Comment by migee** [comment] 2015-11-20 17:09
Thanks, had same and after reading the above I simply added $('#myForm').validator().off('submit'); prior to destroying it. Now everythings good again
