### ISSUE TITLE
Required for select doesn't work well in Safari 9.1.1

### ISSUE THREAD

**Issue by devdemi** [1000hz/bootstrap-validator#358] opened 2016-06-22 16:08 UTC
I have 2 required form elements SELECT. Submit button is still disabled when I choose option in first and second element but if I choose option in both element again button will be enabled and submits form.
My browser is Safari 9.1.1. It works fine in FF and Chrome.
https://jsfiddle.net/11ub14hy/1/

**Comment by 1000hz** [comment] 2016-06-22 16:22
Dupe of #293

**Closed by 1000hz** 2016-06-22 16:22 UTC
