### ISSUE TITLE
Issues with submit button always disabled 

### ISSUE THREAD

**Issue by micheledallatorre** [1000hz/bootstrap-validator#391] opened 2016-08-09 12:38 UTC
I have a form with input text field with custom validator attached, and submit button. 
My problem is somehow similar to https://github.com/1000hz/bootstrap-validator/issues/294.
The submit button has always the class "disabled" attached, even when the input field (hence the form) is successfully validated.

Using the following snippet mentioned in https://github.com/1000hz/bootstrap-validator/issues/294#issuecomment-204072356 does not help, meaning the "disabled" class is never removed from my submit button even though the following function is called (i.e. the form becomes valid).

``` javascript
$( "form" ).on( "valid.bs.validator", function() {
  $( "#submit_button" ).prop("disabled", false);
});

```

The only workaround I found so far is to:
1. remove `type="submit"` property from the button, that becomes then `<button class="btn btn-primary col-md-12" id="submitButton">Submit!</button>`
2. Use the following code to enable/disable the button above (which is not of type submit anymore)

``` javascript
$('#inputForm').on( "valid.bs.validator", function() {
        $('#submitButton').removeClass("disabled");        // enables button
        console.log("VALID FORM");
    });

    $('#inputForm').on( "invalid.bs.validator", function() {
        $('#submitButton').addClass('disabled');
        console.log("INVALID FORM");
    });
```

Why does that happen?
Any better ideas how to solve that?

Thanks

**Comment by cambazz** [comment] 2017-01-20 15:39
Hello,

Adding data-disable="false" to form element will make the button enabled always.

Best

**Comment by chipurichettitarun** [comment] 2017-03-21 14:37
1. what is the use of showing error messages when clicked on disable (submit) button... It shouldn't perform any action as the button is disabled.
2. Clicking on name field, with out giving any input i clicked on submit.. its showing error message only  for that particular field... If disabled (submit) clicked twice its showing error messages for whole form. is that correct??.... ignore if already fixed

**Comment by 1000hz** [comment] 2017-03-21 15:41
Closing this issue since it's old. @micheledallatorre if you still have this issue, please provide an example on JSBin that reproduces your issue and I'll reopen.

@chipurichettitarun If the user fills out a form and overlooks a field, they will not know why the form is disabled. If the button is fully disabled, they have no way of knowing why they can't submit. By allowing them to click the button (or hit Enter) the form will reveal all errors preventing submission. It's for a better user experience.

**Closed by 1000hz** 2017-03-21 15:41 UTC
