### ISSUE TITLE
Form says username and password has not been entered even after auto-complete has filled it in

### ISSUE THREAD

**Issue by rsshilli** [1000hz/bootstrap-validator#585] opened 2017-08-28 19:33 UTC
In Chrome, I have an email and password field both marked as required.  

    <form data-toggle="validator" role="form" id="loginForm">
      <div class="form-group">
          <label for="emailInput" class="control-label">
              Email
          </label>
          <input type="email" class="form-control" placeholder="Email" id="emailInput" data-error="Email address is invalid" required="true"/>
          <div class="help-block with-errors"></div>
      </div>

      <div class="form-group">
          <label for="passwordInput" class="control-label">
              Password
          </label>
          <input type="password" class="form-control" placeholder="Password" id="passwordInput" data-minlength="8" data-error="Password is incorrect.  See password requirements above." required="true"/>
          <div class="help-block with-errors"></div>
      </div>

      <br>
      <div class="form-group">
          <input type="submit" class="btn btn-block btn-lg btn-primary" id="loginButton" value="Login" />
      </div>
    </form>

Everything works great, until you save your username & password with Chrome's password manager.  Then, the next time you try to login, it will fill in the form automatically but the login button will be disabled.  The effect is purely visual.  As soon as you click anywhere on the page (username, password, or even whitespace on the side), the login button will no longer appear disabled. 

Does anybody have a solution for how I can make the login button appear enabled as soon as the autocomplete fills in the data?

**Comment by 1000hz** [comment] 2017-09-05 17:04
Dupe of #26. Seems like the best solution is to use a document ready handler or setTimeout to trigger a `focusout.bs.validator` event on inputs with values.

**Closed as completed by 1000hz** 2017-09-05 17:04 UTC
